import type { Metadata } from "next";
import { LegalProse, LegalSection } from "@/components/legal-prose";

export const metadata: Metadata = {
  title: "Terms of Service — Skill Issue",
  description: "The terms for using Skill Issue.",
};

const EMAIL = "shaansatsangi.cse@gmail.com";

export default function TermsPage() {
  return (
    <LegalProse title="Terms of Service" lastUpdated="2026-05-28">
      <p>
        By using Skill Issue (operated by Shaan Satsangi), you agree to these terms. If you
        don&rsquo;t agree, please don&rsquo;t use the service.
      </p>

      <LegalSection heading="What Skill Issue is">
        <p>
          Skill Issue produces an opinionated, automated analysis of a public GitHub profile for
          insight and entertainment. The scores and commentary are generated by software and may be
          incomplete or wrong. Skill Issue is <strong className="text-foreground">not</strong> an
          authoritative hiring, credit, employment, or background-check tool, and should not be used
          to make decisions about people.
        </p>
      </LegalSection>

      <LegalSection heading="Accounts">
        <p>
          Signing in is optional and uses GitHub OAuth. You are responsible for activity under your
          GitHub account and for keeping it secure.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>abuse, overload, or attempt to disrupt the service;</li>
          <li>scrape it or access it through automated means outside normal use;</li>
          <li>circumvent rate limits or security measures;</li>
          <li>use it to harass others or for unlawful purposes.</li>
        </ul>
      </LegalSection>

      <LegalSection heading="Intellectual property">
        <p>
          The service, its design, and its scoring system belong to us. GitHub data shown in a report
          belongs to its respective owners and GitHub; we present it for analysis.
        </p>
      </LegalSection>

      <LegalSection heading="Disclaimers">
        <p>
          The service is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without
          warranties of any kind. Scores are subjective, automated estimates and are not guarantees
          of skill, quality, or fitness for any purpose.
        </p>
      </LegalSection>

      <LegalSection heading="Limitation of liability">
        <p>
          To the maximum extent permitted by law, we are not liable for any indirect, incidental, or
          consequential damages arising from your use of the service.
        </p>
      </LegalSection>

      <LegalSection heading="Termination">
        <p>
          We may suspend or limit access that abuses the service. You can stop using it and delete
          your saved data at any time.
        </p>
      </LegalSection>

      <LegalSection heading="Governing law">
        <p>These terms are governed by the laws of India.</p>
      </LegalSection>

      <LegalSection heading="Changes">
        <p>
          We may update these terms; the &ldquo;last updated&rdquo; date above reflects the latest
          version. Continued use means you accept the changes.
        </p>
      </LegalSection>

      <LegalSection heading="Contact">
        <p>
          Questions? Email{" "}
          <a
            href={`mailto:${EMAIL}`}
            className="text-foreground underline underline-offset-4 hover:text-accent"
          >
            {EMAIL}
          </a>
          .
        </p>
      </LegalSection>
    </LegalProse>
  );
}
